module Fable.StaticPageGenerator.Main

open Fable.Core.JsInterop
open Fable.Helpers.React
open Helpers
open Fulma

let templatePath = resolve "${entryDir}/../templates/template.hbs"
let markdownPath = resolve "${entryDir}/../posts/home.md"
let indexPath = resolve "${entryDir}/../index.html"

let posts = ["post1"; "post2"]

let navs() =
    div [] [
        h1 [classList [("is-size-1 title", true)] ] ["Joel Vandiver" |> str]
        small [] ["Blog Generated by Fable" |> str]
    ]

let render() =
    [ "title" ==> "Joel Vandiver"
      "navs" ==> (navs() |> parseReactStatic)
      "posts" ==> (posts)
      "post" ==> parseMarkdown markdownPath ]
    |> parseTemplate templatePath
    |> writeFile indexPath

render()
