module Fable.StaticPageGenerator.Main

open Fable.Core.JsInterop
open Fable.Import
open Fable.Helpers.React
open Helpers
open Fulma

let templatePath = resolve "${entryDir}/../templates/template.hbs"
let markdownPath = resolve "${entryDir}/../README.md"
let indexPath = resolve "${entryDir}/../index.html"

let header() =
    div [] [
        h1 [
            classList [("is-size-1", true)] ] [
            "Joel Vandiver" |> str
        ]
        small [] [
            "Blog Generated by Fable" |> str
        ]
    ]

let render() =
    [ "title" ==> "Joel Vandiver"
      "header" ==> (header() |> parseReactStatic)
      "post" ==> parseMarkdown markdownPath ]
    |> parseTemplate templatePath
    |> writeFile indexPath

render()
