module Fable.StaticPageGenerator.Main

open Fable.Core.JsInterop
open Fable.Helpers.React
open Helpers
open Fulma

let templatePath = resolve "${entryDir}/../templates/template.hbs"
let indexPath = resolve "${entryDir}/../index.html"
let postPath = resolve "${entryDir}/../posts.html"

let posts = 
    [
        "${entryDir}/../index.md"
        "${entryDir}/../posts/2018-11-10/test.md"
        "${entryDir}/../posts/2018-11-11/test.md"
        "${entryDir}/../posts/2018-11-17/test.md"
    ]

let navs() =
    div [] [
        h1 [classList [("is-size-1 title", true)] ] ["Joel Vandiver" |> str]
        small [] ["Blog Generated by Fable" |> str]
    ]

let saveFile (markdownPath: string) =
    let path = markdownPath.Replace(".md", ".html")
    [ "title" ==> "Joel Vandiver"
      "navs" ==> (navs() |> parseReactStatic)
      "post" ==> parseMarkdown markdownPath ]
    |> parseTemplate templatePath
    |> writeFile path

let render() = posts |> List.iter saveFile

render()
