#r @"C:\git\joelvandiver.github.io\packages\Fable.Core\lib\netstandard2.0\Fable.Core.dll"
#r @"C:\git\joelvandiver.github.io\packages\Fable.React\lib\netstandard2.0\Fable.React.dll"

open System.IO
open Fable.Helpers.React
open Fable.Core.JsInterop

let postPath = __SOURCE_DIRECTORY__ + @"..\..\posts"

type FileText = 
    {  file : string
       path : string }

let readFileText (path: string)  = 
  { file = File.ReadAllText(path)
    path = path.Replace(postPath, @"\posts") }

let postMds = 
  Directory.GetFiles(postPath, "*.md", SearchOption.AllDirectories)
  |> List.ofSeq
  |> List.map readFileText
  
let posts = 
  Directory.GetFiles(postPath, "*.html", SearchOption.AllDirectories)
  |> List.ofSeq
  |> List.map readFileText

let private marked (markdown: string): string = importDefault "marked"

let parseMarkedFileText (ft: FileText) : FileText =
  { file = ft.file |> marked
    path = ft.path.Replace(".md", ".html")}

let parsed = postMds |> List.map parseMarkedFileText

let navs() =
    div [] [
        h1 [classList [("is-size-1 title", true)] ] ["Joel Vandiver" |> str]
        small [] ["Blog Generated by Fable" |> str]
    ]